### ISSUE TITLE
Attempts to use modulename_help for any plugin type

### ISSUE THREAD

**Issue by mudrd8mz** [berrandonea/moodle-block_catalogue#1]
This code in `blockcatalogue.list.php`:

```
            case 'description' :
                $vendordescription = get_string('modulename_help', $component);
                return $this->control_string($vendordescription);
```

is not correct as the string `modulename_help` is provided by activity modules / resources (plugin type `mod`) only.

![image](https://cloud.githubusercontent.com/assets/85831/16851356/7e1707ba-4a03-11e6-8097-a62ff75dd23b.png)

**Comment by berrandonea** [comment]
Fixed in release 1.1
