### ISSUE TITLE
Error when installing mod_customlabel on Moodle 3.1

### ISSUE THREAD

**Issue by germanvaleroelizondo** [berrandonea/moodle-block_catalogue#4]
Hi,

I have been trying to use your Catalogue plugin for Moodle 3.1 , but the displayed list input box explanation shows ' :Possible values : activities, blocks, customlabels **(requires mod_customlabel),** 

The mod_customlabel available at https://moodle.org/plugins/mod_customlabel only has versions up to Moodle 2.9, but no 3.0 nor 3.1 versions. When I tried to install it, in a new Moodle 3.1 local server, I had this error: (developer debug mode):

Warning: include(G:\M\m31plus\server\moodle/mod/customlabel/type/courseclassifier/version.php): failed to open stream: No such file or directory in G:\M\m31plus\server\moodle\lib\classes\component.php on line 1153

Warning: include(): Failed opening 'G:\M\m31plus\server\moodle/mod/customlabel/type/courseclassifier/version.php' for inclusion (include_path='G:\M\m31plus\server\moodle/lib/pear;.;G:\M\m31plus\server\php\PEAR') in G:\M\m31plus\server\moodle\lib\classes\component.php on line 1153
Unsupported $module syntax detected in version.php of the mod_customlabel plugin.

```
line 322 of \lib\classes\plugin_manager.php: call to debugging()
line 348 of \lib\classes\plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of \lib\classes\plugininfo\base.php: call to core_plugin_manager->get_present_plugins()
line 143 of \lib\classes\plugininfo\base.php: call to core\plugininfo\base->load_disk_version()
line 97 of \lib\classes\plugininfo\base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of \lib\classes\plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of \lib\classes\plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of \lib\classes\plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1132 of \admin\renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of \admin\renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of \admin\index.php: call to core_admin_renderer->upgrade_plugin_check_page()
```

Plugin mod_customlabel does not declare valid $plugin->component in its version.php.

```
line 328 of \lib\classes\plugin_manager.php: call to debugging()
line 348 of \lib\classes\plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of \lib\classes\plugininfo\base.php: call to core_plugin_manager->get_present_plugins()
line 143 of \lib\classes\plugininfo\base.php: call to core\plugininfo\base->load_disk_version()
line 97 of \lib\classes\plugininfo\base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of \lib\classes\plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of \lib\classes\plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of \lib\classes\plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1132 of \admin\renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of \admin\renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of \admin\index.php: call to core_admin_renderer->upgrade_plugin_check_page()
```

Warning: include(G:\M\m31plus\server\moodle/mod/customlabel/type/courseclassifier/version.php): failed to open stream: No such file or directory in G:\M\m31plus\server\moodle\lib\classes\plugin_manager.php on line 318

Warning: include(): Failed opening 'G:\M\m31plus\server\moodle/mod/customlabel/type/courseclassifier/version.php' for inclusion (include_path='G:\M\m31plus\server\moodle/lib/pear;.;G:\M\m31plus\server\php\PEAR') in G:\M\m31plus\server\moodle\lib\classes\plugin_manager.php on line 318
Plugin customlabeltype_courseclassifier does not declare valid $plugin->component in its version.php.

```
line 328 of \lib\classes\plugin_manager.php: call to debugging()
line 348 of \lib\classes\plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of \lib\classes\plugininfo\base.php: call to core_plugin_manager->get_present_plugins()
line 143 of \lib\classes\plugininfo\base.php: call to core\plugininfo\base->load_disk_version()
line 97 of \lib\classes\plugininfo\base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of \lib\classes\plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of \lib\classes\plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of \lib\classes\plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1132 of \admin\renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of \admin\renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of \admin\index.php: call to core_admin_renderer->upgrade_plugin_check_page()
```

Subplugin type "customlabeltype" should define class "\mod_customlabel\plugininfo\customlabeltype"

```
line 467 of \lib\classes\plugin_manager.php: call to debugging()
line 407 of \lib\classes\plugin_manager.php: call to core_plugin_manager::resolve_plugininfo_class()
line 368 of \lib\classes\plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of \lib\classes\plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1132 of \admin\renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of \admin\renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of \admin\index.php: call to core_admin_renderer->upgrade_plugin_check_page()
```

Do you know if there is a version of mod_customlabel available for Moodle 3.1 elsewhere ?

Thanks in advance for your help.

**Comment by berrandonea** [comment]
Hi,

This issue is about mod_customlabel, not block_catalogue. mod_customlabel works on my Moodle 3.1
Perhaps you should contact its author, Valery Fremaux or report an issue there (https://github.com/vfremaux/moodle-mod_customlabel/issues) if it still doesn't work on yours.

Best regards

Brice
