### ISSUE TITLE
Hard-coded English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [berrandonea/moodle-block_catalogue#5]
Hi,

I have been using your Catalogue plugin for Moodle 2.9 and I like it a lot. I already made the translation in AMOS for the Mexican Spanish language pack..

I think this plugin would be even more useful for Moodlers of Languages other than English (eg,, French, Spanish, Italian,...) if several of the hard-coded English language strings used could be replaced by variables that can be translated in AMOS.

May I firstly suggest you to change the text inside the button that says 'Add to course' ? 
Not being a programmer (I am a veterinary pathologist), I guess that this one button-string should not be too difficult to change into a translatable string variable.

Later, may we talk about the likelihood/difficulty of translating the other more visible English language strings for Resources, Activities, enrolments, Grades, Reports and Blocks ?

Thanks in advance for your help and thanks for contribuiting this nice plugin that I am certain will be very useful for many teachers world-wide.

**Comment by germanvaleroelizondo** [comment]
The 'check' button might be an easy one to change.

On the Activities section, hard-wired strings seen are: Exercises , Collaboration , Other .

**Comment by berrandonea** [comment]
Solved in release 1.1.

**Comment by germanvaleroelizondo** [comment]
Hi Brice,
Please observe atached image and notice 'CATÁLOGO' (in Spanish), and 'Favoritos' also in Spanish, but the other strings are in English. When you go into one of the sub-menus, most strings are indeed translated properly.
Can you please install the Mexican Spanish language pack and check the behaviour of your plugin in an AMOS suported language other than french.

Curent status:
![spanish not translated properly](https://cloud.githubusercontent.com/assets/2671923/18561602/3f161852-7b46-11e6-94ed-f864ccccf9e1.png)

**Comment by germanvaleroelizondo** [comment]
By the way, there are 21 not-transalted strings in AMOS in the FRENCH language. They seem to be documentation pages for activities and resources. Can you make some of those DOCUMENTATION pages translations ? Or ask for help in the french Moodle forum ? Maybe those pages are not a top priority and french users can use the English documentation.

**Comment by germanvaleroelizondo** [comment]
Hi Brice.

I have been thinking about your plugin.

If the previous  ZIP file (with the french translations included in a subdirectory) worked fine in French, but the new version is shown in English only, it is highly likely that you have an ilegal (as per AMOS) string declared. AMOS reports 211 string variables. Can you count them in GitHub ?

Please see https://docs.moodle.org/dev/Translating_plugins#Plugins_with_coding_errors 

That is the most likely explanation. Please double check your string variables. I am a veterinary pathologist and I  have not yet learned enough PHP programming to make a code check. SORRY...

Your plugin is very good and it would be even better if it were 100% translatable by AMOS. I have translated 210 of it's strings into Mexican Spanish in AMOS.

**Comment by germanvaleroelizondo** [comment]
Hi Brice.

Could you identify a problem in the string variables declarations?

Would you like me to post a message in the Moodle languages forum and ask for help from Moodle developers, so that someone else can have a look at your code?

**Comment by germanvaleroelizondo** [comment]
Hi Brice,
I just noticed that all the strings with issues (in the /lang/en/block_catalogue.php file) are declared inmediately after one empty line.

I have one silly idea (I am not a programmer), but it would be extremely quick to test.

Can you please replace these empty blank lines with a simple comment line and upload the modified file into the Moodle plugins database, to see if AMOS would now recognize more strings (than the previous 211), as all the strings with issues are not registed in AMOS.

Thanks in advance for your help.

**Comment by germanvaleroelizondo** [comment]
I have posted in https://lang.moodle.org/mod/forum/discuss.php?d=5174 . Please feel free to add/correct/answer as appropiate.

**Comment by berrandonea** [comment]
Hello German, 

Thanks your help and the time you spend on this. These blank lines may well be the explaination for the strings that are not translated on your spanish platform.

The problem I face on my new site is different : no string at all is translated. But I think I found the answer to this in the link you showed to me : I had to clear the cache and wait for an hour. This means most strings should be fine when I wake up tomorrow, except those that bug on your side too. Then, I'll try to remove the blank lines.

Thanks again and have a good night.

Regards

Brice

**Comment by germanvaleroelizondo** [comment]
Thanks Brice. 
It is nearly 5 pm in Mexico and today is the Mexican Independence day. 
I think I'll have a drink now.

Regards,

Germán

**Comment by berrandonea** [comment]
Cool, so I guess you did have a good night. ;)

I just published a new version in the plugins directory, without the blank lines. We'll see if it fixes your bug.

Mine is still puzzling : even after clearing the cache and waiting a whole night, all the texts still display in English.

**Comment by berrandonea** [comment]
Ok, it was obvious : I had simply forgotten to create a crontab on my new server. Here's why AMOS was not queried at all.

**Comment by berrandonea** [comment]
Good. With the cron activated, most of the strings are now translated.

**Comment by berrandonea** [comment]
Oh, I get it ! It's a coding problem. I have to correct this.

**Comment by berrandonea** [comment]
Alright ! It's fixed, now. I've sent the fixed version to the plugins directory.

**Comment by germanvaleroelizondo** [comment]
Thanks Brice. I'll check it right now .

**Comment by germanvaleroelizondo** [comment]
The new version works beautifully. Congratulations. I will close this issue now.
