### ISSUE TITLE
Moodle documentation for this plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [berrandonea/moodle-block_catalogue#8]
Hi Brice,

I hope you don't mind that I created a Moodle Docs page at https://docs.moodle.org/31/en/blocks/catalogue . It would be very good if you could link to this Moodle Docs page in the Useful links section of https://moodle.org/plugins/block_catalogue.

I liked very much the fact that the activities descriptions are already translated in many languages (eg, German and Japanese).

Moodle Docs pages are very easy to translate for users of languages other than English. I have added a Spanish translation; Maybe you would like to create the French version.

Please feel free to add/remove/change as you see fit.

Greetings,

Germán

**Comment by berrandonea** [comment]
Thank you for creating this page. I'll try to find time to work on it and describe the plugin's features, depending on the user's role. 

Best regards

Brice
