### ISSUE TITLE
possible future improvement

### ISSUE THREAD

**Issue by germanvaleroelizondo** [berrandonea/moodle-block_catalogue#9]
Hi Bruce,
I was thinking, could you replace some of your plugin variable strings and instead use some of Moodle core language strings?. 
This way, most of these strings would have already been translated in the standard Moodle core language packs (eg, Japanese).

Eg, the string for "Resources" is declared in resources | core
"Activities" is in activities | core
"Grades" is in grades | core
"Reports" is in reports | core
"Blocks" is in blocks | core
"Add..." is in  adddots | core
"Other" is in other | mod_data
"Enrolment methods" is in enrolmentmethods | core
"Check" is in check | core
"Users" is in users | core
"Grade report" is in gradereport | core_grades
"Grade settings" is in gradessettings | core_grades
"Outcomes" is in outcomes | core_grades
"Competencies" is in competencies | core_competency
"Badges" is in badges | core_badges

But I am not a programmer, and I do not know if that would be possible/easy/forbidden.

**Comment by berrandonea** [comment]
I think it's possible, at least for some of these strings. I'll check this.

**Comment by germanvaleroelizondo** [comment]
Thanks.
